In [1]:
from datascience import *
import numpy as np

## Review

**Discussion Question 1:** Question 1, Final, Fall 2019.
- What will the following Python expression evaluate to?

In [2]:
make_array(1,2,3) * 2

array([2, 4, 6])

**Discussion Question 2:**    
- What will the following Python expression evaluate to?


In [3]:
make_array(1,2,3) + np.arange(start=1, stop=4)

array([2, 4, 6])

____

## New material

### Two ways to create tables

**Way 1:** Reading from a file

In [4]:
nba = Table.read_table('nba_salaries.csv')
nba.show(6)

**Way 2:** Creating from scratch

In [5]:
streets = make_array('Bancroft', 'Durant', 'Channing', 'Haste')
streets

array(['Bancroft', 'Durant', 'Channing', 'Haste'],
      dtype='<U8')

In [6]:
Table()

In [7]:
southside = Table().with_column('Streets', streets)
southside

Streets
Bancroft
Durant
Channing
Haste

In [8]:
southside.with_column('Blocks from campus', np.arange(4))

Streets  | Blocks from campus
Bancroft | 0
Durant   | 1
Channing | 2
Haste    | 3

In [9]:
Table().with_columns(
    'Streets', streets,
    'Blocks from campus', np.arange(4)
)

Streets  | Blocks from campus
Bancroft | 0
Durant   | 1
Channing | 2
Haste    | 3

### W.E.B. DuBois was a data scientist!

In [10]:
du_bois = Table.read_table('du_bois.csv')

In [19]:
du_bois.show(du_bois.num_rows)

**Task**: Find the number of rows and the number of columns in this table.

In [13]:
du_bois.num_rows, du_bois.num_columns

(7, 8)

**Task:** Find all of the information (all of the variables) recorded on each "individual" in this table.

In [17]:
du_bois.labels

('CLASS',
 'ACTUAL AVERAGE',
 'RENT',
 'FOOD',
 'CLOTHES',
 'TAXES',
 'OTHER',
 'STATUS')

**Task:** Extract just the information (row(s)) of the families with the highest earning income bracket on average, circa 1900. 
- There are multiple correct ways to do this! See if you can find more than one.

Way 1:

In [20]:
du_bois.where('ACTUAL AVERAGE', are.above_or_equal_to(np.max(du_bois.column('ACTUAL AVERAGE'))))

CLASS         | ACTUAL AVERAGE | RENT | FOOD | CLOTHES | TAXES | OTHER | STATUS
1000 and over | 1125           | 0    | 0.29 | 0.16    | 0.045 | 0.505 | WELL-TO-DO

Way 2:

In [21]:
du_bois.sort('ACTUAL AVERAGE', descending=True).take(0)

CLASS         | ACTUAL AVERAGE | RENT | FOOD | CLOTHES | TAXES | OTHER | STATUS
1000 and over | 1125           | 0    | 0.29 | 0.16    | 0.045 | 0.505 | WELL-TO-DO

Discussion [1 min]

**Task:** Based on the relevant variables in the table, estimate the amount of money each that each income class of Black Americans spent on food, circa 1900.
- Discussion [1 min]

In [24]:
du_bois.column('ACTUAL AVERAGE')*du_bois.column('FOOD')

array([  59.813 ,  117.2415,  144.3338,  160.5134,  169.57  ,  325.6   ,
        326.25  ])

**Task:** Add these estimates to the `du_bois` table as a new column.

In [23]:
du_bois.with_column('AMOUNT OF MONEY' ,du_bois.column('ACTUAL AVERAGE')*du_bois.column('FOOD'))

CLASS         | ACTUAL AVERAGE | RENT | FOOD | CLOTHES | TAXES | OTHER | STATUS      | AMOUNT OF MONEY
100-200       | 139.1          | 0.19 | 0.43 | 0.28    | 0.001 | 0.099 | POOR        | 59.813
200-300       | 249.45         | 0.22 | 0.47 | 0.23    | 0.04  | 0.04  | POOR        | 117.241
300-400       | 335.66         | 0.23 | 0.43 | 0.18    | 0.045 | 0.115 | FAIR        | 144.334
400-500       | 433.82         | 0.18 | 0.37 | 0.15    | 0.055 | 0.245 | FAIR        | 160.513
500-750       | 547            | 0.13 | 0.31 | 0.17    | 0.05  | 0.34  | COMFORTABLE | 169.57
750-1000      | 880            | 0    | 0.37 | 0.19    | 0.08  | 0.36  | COMFORTABLE | 325.6
1000 and over | 1125           | 0    | 0.29 | 0.16    | 0.045 | 0.505 | WELL-TO-DO  | 326.25

____

### Back to the NBA example!

**Task:**
- Extract the rows in the `nba` table that correspond to Stephen Curry from the years 2016, 2017, ..., 2020. 
- Save the table into the name `recent_curry`.

In [28]:
nba.where('name', 'Stephen Curry').where('season', are.between_or_equal_to(2016, 2020))

rank | name          | position | team                  | salary   | season
61   | Stephen Curry | PG       | Golden State Warriors | 11370786 | 2016
82   | Stephen Curry | PG       | Golden State Warriors | 12112359 | 2017
1    | Stephen Curry | PG       | Golden State Warriors | 37457154 | 2018
1    | Stephen Curry | PG       | Golden State Warriors | 37457154 | 2019
1    | Stephen Curry | PG       | Golden State Warriors | 40231758 | 2020

In [29]:
recent_curry = nba.where('name', 'Stephen Curry').where('season', are.between_or_equal_to(2016, 2020))

**Discussion Question 3:** 
- Which of the following two lines of code correctly calculates the average salary of Steph Curry from 2016-2020?
- Use the [Python reference sheet](https://www.data8.org/sp25/reference/) to help you answer!

In [30]:
np.average(recent_curry.select('salary'))

TypeError: the resolved dtypes are not compatible with add.reduce. Resolved (dtype('<U6'), dtype('<U6'), dtype('<U12'))

In [31]:
np.average(recent_curry.column('salary'))

27725842.199999999